//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesMarketPlaceEntities : DbContext
    {
        public NotesMarketPlaceEntities()
            : base("name=NotesMarketPlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Downloads> Downloads { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<NotesStatus> NotesStatus { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
        public virtual DbSet<SellerNoteAttachment> SellerNoteAttachment { get; set; }
        public virtual DbSet<SpamReports> SpamReports { get; set; }
        public virtual DbSet<SystemConfigurations> SystemConfigurations { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersProfile> UsersProfile { get; set; }
        public virtual DbSet<UsersReviews> UsersReviews { get; set; }
    }
}
