//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notes()
        {
            this.Downloads = new HashSet<Downloads>();
            this.SellerNoteAttachment = new HashSet<SellerNoteAttachment>();
            this.SpamReports = new HashSet<SpamReports>();
            this.UsersReviews = new HashSet<UsersReviews>();
        }
    
        public int NoteID { get; set; }
        public string NotesDp { get; set; }
        public int SellerID { get; set; }
        public string NotesTitle { get; set; }
        public int NotesCategory { get; set; }
        public int NotesType { get; set; }
        public string UniversityInformation { get; set; }
        public int Country { get; set; }
        public string CourseName { get; set; }
        public int CourseCode { get; set; }
        public string Professor { get; set; }
        public string SellType { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string PreviewUpload { get; set; }
        public Nullable<int> NoOfPages { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> NotesPublishedDateTime { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<bool> IsInappropriate { get; set; }
        public int Status { get; set; }
        public Nullable<int> ActionedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Downloads> Downloads { get; set; }
        public virtual Notes Notes1 { get; set; }
        public virtual Notes Notes2 { get; set; }
        public virtual Notes Notes11 { get; set; }
        public virtual Notes Notes3 { get; set; }
        public virtual Notes Notes12 { get; set; }
        public virtual Notes Notes4 { get; set; }
        public virtual Notes Notes13 { get; set; }
        public virtual Notes Notes5 { get; set; }
        public virtual NotesStatus NotesStatus { get; set; }
        public virtual Type Type { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNoteAttachment> SellerNoteAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamReports> SpamReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersReviews> UsersReviews { get; set; }
    }
}
